SELECT DISTINCT ?entity ?category ?labelCategory ?typeCategory
WHERE {
        ?entity askomicsns:entity "true"^^xsd:boolean .
        ?category askomicsns:attribute "true"^^xsd:boolean ;
                    rdf:type owl:ObjectProperty;
                    rdfs:label ?labelCategory ;
                    rdfs:domain ?entity;
                    rdfs:range ?typeCategory.

	    VALUES ?entity { $entities }
}
