SELECT DISTINCT ?entity ?attribute ?labelAttribute ?typeAttribute
WHERE {
        ?entity askomicsns:entity "true"^^xsd:boolean .
	      ?attribute askomicsns:attribute "true"^^xsd:boolean .

        ?attribute rdf:type owl:DatatypeProperty;
					         rdfs:label ?labelAttribute ;
                   rdfs:domain ?entity;
                   rdfs:range ?typeAttribute.

	    VALUES ?entity { $entities }
		VALUES ?typeAttribute { xsd:decimal xsd:string }
}
