SELECT DISTINCT ?relation ?property ?value
WHERE {
      ?relation rdf:type owl:ObjectProperty;
                rdfs:domain ?subject;
                rdfs:range ?object.

      ?subject askomicsns:entity "true"^^xsd:boolean .
      ?object askomicsns:entity "true"^^xsd:boolean .

      ?relation ?property ?value.
}
