SELECT DISTINCT ?relation_label
WHERE {
        ?class askomicsns:entity "true"^^xsd:boolean .
        OPTIONAL { ?relation rdfs:domain ?class } .
        OPTIONAL { ?relation rdfs:range ?range } .
        OPTIONAL { ?relation rdfs:label ?relation_label } .
        VALUES ?class { :$nodeClass }
}
