SELECT DISTINCT ?nodeUri ?nodeLabel
WHERE {
        ?nodeUri askomicsns:entity "true"^^xsd:boolean .
        ?nodeUri askomicsns:startPoint "true"^^xsd:boolean .
        ?nodeUri rdfs:label ?nodeLabel
}
