SELECT DISTINCT ?nodeUri ?nodeLabel
WHERE {
    GRAPH <urn:sparql:tests-askomics:insert:informative1> {
    ?g rdfg:subGraphOf <urn:sparql:tests-askomics:insert:informative1> }
    GRAPH ?g {
        ?nodeUri askomicsns:entity "true"^^xsd:boolean .
        ?nodeUri askomicsns:startPoint "true"^^xsd:boolean .
        ?nodeUri rdfs:label ?nodeLabel
    }
}
